[package]
name = "gravibot-engine"
version = "0.1.0"
edition = "2021"
resolver = "2"

[dependencies]
winit = "0.26"
env_logger = "0.9"
log = "0.4"
wgpu = "0.13"
pollster = "0.2"
bytemuck = "1.10"
image = { version = "0.24", default-features = false }
